.TH WHISPER-ECHO-GTK 1 "2026-08-13" "whisper-echo-gtk 0.1" "User Commands"
.SH NAME
whisper\-echo\-gtk \- GTK4 GUI frontend for whisper\-echo
.SH SYNOPSIS
.B whisper\-echo\-gtk
.SH DESCRIPTION
whisper\-echo\-gtk provides a native GNOME desktop interface to configure whisper\-echo settings, start/stop the dictation engine, monitor live status and transcription, and persist preferences.
.SH OPTIONS
No command line options.
.SH FILES
.I ~/.whisper-echo/whisper-echo.conf
.SH SEE ALSO
whisper\-echo(1)
.SH AUTHOR
Bryan Nielsen <bnielsen1965@gmail.com>
